GET http://localhost:8000/products/ HTTP/1.1

### 

GET http://localhost:8000/products/2/ HTTP/1.1

### 

DELETE http://localhost:8000/products/1/ HTTP/1.1

### 

PUT http://localhost:8000/products/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1MjMzODU3LCJpYXQiOjE3MzUyMzM1NTcsImp0aSI6IjFhMmYyNWI3ZTU3MDRmOTU5MmU4NjZjZjc3NTVlZTI1IiwidXNlcl9pZCI6MX0.cakcVsw9SIZMsVtAVALuDJGo9utwUVVB552jHwKCaP4

{
    "name": "Television",
    "price": 300.00,
    "stock": 14,
    "description": "An amazing new TV"
}

### 

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1MjMyMjM3LCJpYXQiOjE3MzUyMzE5MzcsImp0aSI6IjEyZTQ2YjA2Yzc2MDRiYTk5NTBjZWUxZWQ3OTE2Njk1IiwidXNlcl9pZCI6Mn0.kGxSJHNgrdovNH50YgizsukE1wlTXk4_zdaRflr-b5U

{
    "name": "Television",
    "price": 300.00,
    "stock": 14,
    "description": "An amazing new TV"
}

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "test"
}

###

GET http://localhost:8000/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1MjMyMjM3LCJpYXQiOjE3MzUyMzE5MzcsImp0aSI6IjEyZTQ2YjA2Yzc2MDRiYTk5NTBjZWUxZWQ3OTE2Njk1IiwidXNlcl9pZCI6Mn0.kGxSJHNgrdovNH50YgizsukE1wlTXk4_zdaRflr-b5U

###

POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNTMxODkxNywiaWF0IjoxNzM1MjMyNTE3LCJqdGkiOiIwNGJjM2M3YTdjZjk0MDkyODE0NDZiNTE0YTA3OTAwMSIsInVzZXJfaWQiOjF9.JT1RXrlvL8dtfsbJBHPvaWy6roNyVx6SkG3iAwNpank"
}

###

GET http://localhost:8000/orders/ HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1MzIwMDkxLCJpYXQiOjE3MzUzMTk3OTEsImp0aSI6IjZiYjJjMjdkYzM4YjRkOWI4OWVhMGEwNmU4YWJmMTlkIiwidXNlcl9pZCI6MX0.lNd43Q9BNK23xrFyN-7wKTit5LE4j01HZzwMIlm1a3Q